[package]
name = "hashed-permutation"
version = "1.0.0"
authors = ["Afnan Enayet <afnan@afnan.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
