[package]
name = "hashed-permutation"
description = "A fast, instant-access way to permute a range of numbers"
repository = "https://github.com/afnanenayet/hashed-permutation.git"
keywords = ["hashed", "permutation", "permute", "fast", "instant"]
version = "2.0.0"
authors = ["Afnan Enayet <afnan@afnan.io>"]
edition = "2018"
license = "MIT"
readme = "docs/README.md"

[badges]
azure-devops = { project = "afnanenayet/hashed-permutation", pipeline = "afnanenayet.hashed-permutation" }
maintenance = { status = "actively-developed" }

[dependencies]
failure = { version = "0.1", optional = true }

[features]
default = []
failure-crate = ["failure"]
